BLOOMS_PROMPTS = {
    "remember": (
        "Generate questions that primarily test remembering "
        "facts, definitions, terms, and basic recall."
    ),
    "understand": (
        "Generate questions that primarily test understanding, "
        "explanation, interpretation, and comprehension."
    ),
    "apply": (
        "Generate questions that primarily test applying "
        "knowledge to practical situations and problem solving."
    ),
    "analyze": (
        "Generate questions that primarily test analysis, "
        "comparison, classification, reasoning, and relationships."
    ),
    "evaluate": (
        "Generate questions that primarily test evaluation, "
        "judgment, critical thinking, and decision making."
    ),
    "mixed": (
        "Generate a balanced mix of Remember, Understand, "
        "Apply, Analyze, and Evaluate questions."
    ),
}


def build_analysis_prompt(
    content,
    language,
):
    return f"""
Document Language: {language}

You will receive educational content.

The content may be:

- Plain text
- OCR extracted text
- A structured document analysis generated by an AI system.

If the content contains document structure such as pages, headings,
figures, tables, equations, graphs or summaries, use all of that
information while identifying concepts.

Focus on educational meaning rather than formatting.

Analyze the following content in its original language.

Extract:

- Main topics
- Important keywords
- Definitions
- Processes
- Cause and effect relationships
- Examples
- Formulas
- Numerical facts
- Important names
- Important places
- Important years
- Important terms

Focus on concepts instead of copying sentences.

Return concise structured notes only.

Content:

{content}
"""


def build_question_prompt(
    *,
    content,
    language,
    difficulty,
    blooms_level,
    question_count,
):
    blooms_instruction = BLOOMS_PROMPTS.get(
        blooms_level,
        BLOOMS_PROMPTS["mixed"],
    )

    return f"""
You are an expert exam question generator for an educational assessment platform.

DOCUMENT LANGUAGE:
{language}

Generate every question, option, answer, explanation, and visual label/text in {language}.

Generate exactly {question_count} multiple-choice questions.

# INDEPENDENT QUESTION GENERATION

Generate each question independently.

For every question:

1. Determine the question concept and information required to answer it.
2. Determine whether a visual is required.
3. If a visual is required, independently generate the visual for that question.
4. Keep the question, visual, options, answer, and explanation internally
   consistent.

When multiple questions require visuals, do not automatically reuse the
visual structure or data from another question.

Each visual-required question independently determines:

- visual structure;
- number of objects or sets;
- object/set names;
- numerical values;
- relationships;
- region membership.

Visual variation is required when naturally supported by the question.
Correctness and consistency always have priority.

For example, Venn-diagram questions may independently use:

- 2 sets;
- 3 sets;
- different set names;
- different numerical values;
- different region membership patterns.

Do not force every question to use the same number of sets or objects.

Do not copy a visual from an earlier question and change only the question
text, options, or correct answer.

The visual is part of the current question and must be generated specifically
for that question.

DIFFICULTY:
{difficulty}

BLOOM'S TAXONOMY:
{blooms_instruction}


# SOURCE CONTENT

{content}

Use relevant information from the source content to create self-contained,
academically correct questions.

Do not add unsupported facts, concepts, or relationships.


# MATHEMATICAL NOTATION

- Use LaTeX for mathematical expressions, equations, formulas, fractions,
  powers, roots, inequalities, and mathematical symbols.
- Use inline LaTeX with $...$ inside question_text, options, and explanation.
- Prefer LaTeX over Unicode mathematical notation.
- Do not use Unicode superscripts or subscripts when LaTeX can represent them.
- Keep all mathematical expressions mathematically correct.
- Use standard LaTeX notation.
- The final response must remain valid JSON.
- Escape LaTeX backslashes according to standard JSON string escaping.


# QUESTION RULES

1. Generate questions from the provided source content.

2. Questions may be text-based, mathematical, reasoning-based, figure-based,
   diagram-based, graph-based, or another appropriate educational type.

3. Do not create a visual merely because the source contains a figure.

4. A visual is required only when the generated question itself depends on
   a visual to understand or answer the question.

5. When a visual is required:

   "visual_required": true

   and select the appropriate "visual_type".

6. When a visual is not required:

   "visual_required": false,
   "visual_type": null

7. The visual represents the figure presented WITH THAT QUESTION.

8. The visual must represent the question, not its solution or explanation.

9. Each generated question independently determines its own visual.
   Do not automatically reuse another question's visual.

10. Do not reuse another question's visual structure, labels, values, or
    relationships unless the current question genuinely requires the same
    unchanged visual.

11. If a question changes or modifies a visual situation, only generate it
    when the resulting visual can be completely represented by the supported
    visual semantic data.

12. Do not invent unsupported facts or educational relationships.

13. Questions must be self-contained.

14. Generate exactly four options.

15. Only one option may be correct.

16. "correct_answer" must be one of:
    "A", "B", "C", "D"

17. Options must be plausible and unambiguous.

18. Do not duplicate options.


# EXPLANATION RULES

The explanation must concisely(in short) explain why the correct answer is correct.

Do not explain why the other options are wrong.

Do not refer to options as "Option A", "Option B", etc. unless absolutely
necessary.

The explanation must be consistent with the generated question and visual.

- Return only the final, corrected explanation and solution.
Do NOT include extra fields for analysis, reasoning, planning, notes,
validation, or commentary.

Do NOT write phrases such as:
"I will..."
"Let me..."
"Let's..."
"Final check..."
"Re-ordering..."
"Seems good..."
"I need exactly..."
"I'll ensure..."
"My earlier..."
"This would require..."
"Let me re-confirm..."
"I will use..."
- If you detect an error while solving, silently correct it and return only the final correct solution.
- Keep the explanation concise and logically ordered.
- Use escaped newline characters (`\n`) inside JSON string values. Never insert literal line breaks inside a JSON string.


# VISUAL OUTPUT

Currently supported visual types:

- "venn"
- "geometry"
- "graph"

Future visual types will be added independently.

Do not apply the rules of one visual type to another visual type.

A visual must contain semantic educational information only.

Do NOT generate:

- SVG
- HTML
- CSS
- coordinates
- pixel positions
- bounding boxes
- renderer instructions
- styling instructions
- drawing instructions

The frontend is responsible for rendering the semantic data.


# VISUAL TYPE: VENN

When:

"visual_required": true

and:

"visual_type": "venn"

return:

"visual": {{
    "elements": [...],
    "relationships": [...]
}}

The Venn semantic data must describe the exact Venn diagram required by
the generated question.

The number of sets is determined by the question. It may be 2 sets, 3 sets,
or another supported structure.

Set names, values, and regions must be generated for the current question.
Do not assume a fixed Venn diagram.

For each meaningful value or label, explicitly describe its set membership
and non-membership.

Do not rely on visual proximity to determine membership.

Elements may use:

- circle
- square
- rectangle
- triangle
- polygon
- dot
- label

An element may contain relevant properties such as:

- id
- type
- label
- text
- value

Relationships may describe:

- overlaps
- belongs_to_region
- not_in_region
- inside
- outside

For a value inside multiple sets, list every containing set.

For a value outside a set, explicitly include that set in "not_in".

Do not include sets, values, regions, or relationships that do not exist
in the question's required figure.


# GEOMETRY VISUAL

When the question depends on a geometric figure:

"visual_required": true,
"visual_type": "geometry"

Return:

"visual": {{
  "elements": [],
  "relationships": []
}}

The geometry visual must describe the figure semantically.
Do not generate SVG, coordinates, CSS, HTML, styling, or drawing instructions.

## Supported geometry elements

Supported element types:

- "point"
- "line"
- "segment"
- "ray"
- "triangle"
- "rectangle"
- "square"
- "circle"
- "angle"
- "label"

Each element should contain only the properties required by the question:

- "id"
- "type"
- "label"
- "text"
- "value"
- "value_expression"

Use stable IDs based on the element itself.

Examples:

{{
  "id": "point_a",
  "label": "A",
  "type": "point"
}}

{{
  "id": "segment_ab",
  "label": "AB",
  "type": "segment"
}}

{{
  "id": "angle_abc",
  "label": "∠ABC",
  "type": "angle",
  "value": 40
}}

{{
  "id": "segment_ab",
  "label": "AB",
  "type": "segment",
  "value_expression": "2x + 5"
}}

## Supported relationships

Use only relationships required to describe the figure:

Supported relationships:

- "forms_triangle"
- "connected_to"
- "lies_on"
- "collinear"
- "parallel_to"
- "perpendicular_to"
- "equal_to"
- "midpoint_of"
- "intersects"
- "has_angle"
- "has_length"
- "has_radius"
- "has_value"
- "has_length_relationship"

A relationship uses the following general structure:

{{
  "elements": ["element_id_1", "element_id_2"],
  "type": "relationship_type"
}}

For a relationship involving one element:

{{
  "element_id": "element_id",
  "type": "relationship_type",
  "value": 90
}}

For a relationship involving a target:

{{
  "elements": ["element_id_1", "element_id_2"],
  "target": "element_id",
  "type": "relationship_type"
}}

## Measurement rules

Use:

- "value" for a known numeric measurement.
- "value_expression" for an algebraic measurement.

Examples:

{{
  "element_id": "angle_a",
  "type": "has_angle",
  "value": 90
}}

{{
  "element_id": "segment_ab",
  "type": "has_length",
  "value": 8
}}

{{
  "element_id": "segment_ab",
  "type": "has_length",
  "value_expression": "3x + 5"
}}

{{
  "elements": ["point_a", "point_d"],
  "type": "connected_to"
}}

## Geometry representation rules

1. Represent the actual figure required by the question.

2. Include enough semantic information for the figure to be reconstructed.

3. Include only information relevant to the question.

4. Never include coordinates, SVG, styling, layout instructions, or renderer instructions.

5. Never encode the solution into the figure.

6. Preserve every given geometric measurement and relationship exactly.

7. If a point lies on a segment, explicitly represent it with "lies_on".

8. If multiple points lie on the same line, explicitly represent them with "collinear".

9. If two segments are parallel, explicitly represent "parallel_to".

10. If two segments are perpendicular, explicitly represent "perpendicular_to".

11. If two segments or angles are equal, explicitly represent "equal_to".

12. If a point is a midpoint, explicitly represent "midpoint_of".

13. If two lines or segments intersect at a named point, explicitly represent "intersects".

14. If a triangle is present, explicitly identify its three vertices using "forms_triangle".

15. Additional points on a triangle must not replace the triangle's three vertices.

16. An extension of a triangle side must be represented using a point/line/segment relationship such as "collinear" and must not replace the triangle itself.

17. A point lying on a triangle side must be represented separately using "lies_on".

18. Do not assume a relationship merely because it is mathematically implied. Include relationships that are explicitly needed to reconstruct the stated figure.

19. The visual must represent the question, not the answer.

20. Generate the geometry independently for each question.

21. Never copy geometry measurements or relationships from another question.

22. Mathematical correctness has priority over visual variation.


## Triangle rules

For every triangle:

- Include the three triangle vertices as points.
- Include the three triangle sides as segments when they are needed to reconstruct the figure.
- Include one "forms_triangle" relationship containing exactly the three triangle vertex IDs.
- Every segment that represents an explicitly drawn geometric connection between two points must have a corresponding "connected_to" relationship containing those two point IDs.

Example:

{{
  "elements": [
    {{
      "id": "point_a",
      "label": "A",
      "type": "point"
    }},
    {{
      "id": "point_b",
      "label": "B",
      "type": "point"
    }},
    {{
      "id": "point_c",
      "label": "C",
      "type": "point"
    }}
  ],
  "relationships": [
    {{
      "elements": [
        "point_a",
        "point_b",
        "point_c"
      ],
      "type": "forms_triangle"
    }}
  ]
}}

### Structural Completeness Rule

The visual must contain every segment required to actually draw the stated geometry.

If a triangle or polygon is declared through a `forms_triangle` relationship, the corresponding boundary segments must also be present in `elements` and represented by `connected_to` relationships.

For example, if:
{{
  "elements": ["point_a", "point_b", "point_c"],
  "type": "forms_triangle"
}}

then the visual must contain:
- segment_ab
- segment_bc
- segment_ca

and corresponding:
- A-B connected_to
- B-C connected_to
- C-A connected_to

For composite figures, include all explicitly drawn internal segments and all segments required to connect stated points.

Do not rely on `forms_triangle` alone to imply drawable segments.

For intersections:
- include the intersecting segments;
- include the intersection point;
- include the four resulting point-to-intersection connections when those portions are part of the visible figure.

The visual JSON must be sufficient for the frontend to reconstruct the complete figure without guessing missing segments.

## Important

The geometry JSON is a semantic description only.

The frontend is responsible for:

- geometry detection
- coordinate calculation
- figure orientation
- positioning
- labels
- measurements
- SVG rendering

Do not generate frontend-specific information.

The frontend is responsible for converting this semantic geometry JSON into the visual figure.

### Visual Consistency Rules

- Every drawn segment connecting two named points must have a corresponding `connected_to` relationship containing those two point IDs.
- Do not include extra points, segments, diagonals, cevians, or construction lines unless they are explicitly required by the question or required to construct the target figure.
- Every visual element must have a clear purpose supported by the question or by another stated relationship.

Rules:
- "expression" must be the complete equation in LaTeX.
- "variables" describes only meaningful unknown variables.
- "relationships" describes only important mathematical relationships.
- Generate the equation independently for the current question.
- Do not copy an equation or its values from another question.
- The equation, question, options, answer, and explanation must remain consistent.
- Do not generate SVG, coordinates, styling, or renderer instructions.
- The frontend is responsible for rendering the equation.


GRAPH VISUAL RULE

When a question requires a graph, set:

"visual_required": true,
"visual_type": "graph"

and return a "visual" object using ONLY the following structure:

"visual": {{
  "graph_type": "...",
  "elements": [...],
  "relationships": [...]
}}

Supported graph_type values:

- "line_graph"
- "bar_graph"
- "coordinate_graph"
- "function_graph"
- "number_line"

Supported element types:

- "axis"
- "point"
- "line"
- "curve"
- "bar"
- "label"
- "intersection"
- "highlight"

Supported relationship types:

- "plotted_on"
- "connected_to"
- "intersects"
- "passes_through"
- "parallel_to"
- "perpendicular_to"
- "equal_to"
- "highlighted"
- "has_value"
- "has_label"

Example - line graph
{{
  "visual_required": true,
  "visual_type": "graph",
  "visual": {{
    "graph_type": "line_graph",
    "elements": [
      {{
        "id": "axis_x",
        "type": "axis",
        "label": "Time (hours)"
      }},
      {{
        "id": "axis_y",
        "type": "axis",
        "label": "Distance (km)"
      }},
      {{
        "id": "point_1",
        "type": "point",
        "label": "(0,0)",
        "x": 0,
        "y": 0
      }},
      {{
        "id": "point_2",
        "type": "point",
        "label": "(2,10)",
        "x": 2,
        "y": 10
      }},
      {{
        "id": "line_1",
        "type": "line",
        "label": "Distance"
      }}
    ],
    "relationships": [
      {{
        "elements": ["point_1", "line_1"],
        "type": "plotted_on"
      }},
      {{
        "elements": ["point_2", "line_1"],
        "type": "plotted_on"
      }}
    ]
  }}
}}
Example - bar graph
{{
  "visual_required": true,
  "visual_type": "graph",
  "visual": {{
    "graph_type": "bar_graph",
    "elements": [
      {{
        "id": "category_math",
        "type": "bar",
        "label": "Math",
        "value": 40
      }},
      {{
        "id": "category_science",
        "type": "bar",
        "label": "Science",
        "value": 30
      }},
      {{
        "id": "category_english",
        "type": "bar",
        "label": "English",
        "value": 50
      }}
    ],
    "relationships": [
      {{
        "elements": ["category_math"],
        "type": "has_value",
        "value": 40
      }},
      {{
        "elements": ["category_science"],
        "type": "has_value",
        "value": 30
      }},
      {{
        "elements": ["category_english"],
        "type": "has_value",
        "value": 50
      }}
    ]
  }}
}}

For every graph, provide enough semantic information for the frontend renderer to reconstruct the graph.

IMPORTANT:
- Do NOT generate SVG.
- Do NOT generate HTML.
- Do NOT provide pixel coordinates.
- Do NOT describe visual appearance in natural language.
- Use only the supported graph_type, element types, and relationship types.
- If the question does not require a graph, use:
  "visual_required": false,
  "visual_type": null
  and do not include a visual object.
- Do not create a graph merely because numbers appear in the question.
- The graph must represent information that is necessary or useful for solving or understanding the question.
# FUTURE VISUAL TYPES

Additional visual types will be added here:

 
- circuit
- chart
- table
- other

Each visual type will receive its own small semantic contract.

Do not apply Venn-specific rules to future visual types.


# VISUAL VARIATION

When multiple questions require visuals, independently construct the visual
for each question.

Never reuse another question's complete visual data.

For Venn diagrams:

- Use 2 or 3 sets according to the current question.
- Vary set names when appropriate.
- Vary numerical region values when appropriate.
- Generate memberships from the current question.
- Do not reuse the same complete elements, values, and memberships from
  another question.
- Do not change a visual merely to create variation if that would make the
  question incorrect or ambiguous.

Before returning each question, verify that its visual independently matches
its own question, answer, and explanation.



# FINAL JSON FORMAT

Return ONLY valid JSON.

The top-level structure MUST be:

{{
    "data": [
        {{
            "question_text": "...",
            "option_a": "...",
            "option_b": "...",
            "option_c": "...",
            "option_d": "...",
            "correct_answer": "A",
            "explanation": "...",
            "visual_required": false,
            "visual_type": null
        }}
    ]
}}

1. Parse JSON
2. Check correct_answer is A/B/C/D
3. Compare correct_answer against the option values
4. If explanation contains an obvious final numeric answer, compare it
5. If mismatch → repair/regenerate only that question

When a question requires a visual, add:

When a question requires a Venn diagram, include:
"visual_required": true,
"visual_type": "venn",
"visual": {{
    "elements": [...],
    "relationships": [...]
}}

When a question requires a geometry figure, include:
"visual_required": true,
"visual_type": "geometry",
"visual": {{
    "elements": [...],
    "relationships": [...]
}}

When a question requires a graph, include:
"visual_required": true,
"visual_type": "graph",
"visual": {{
    "elements": [...],
    "relationships": [...]
}}

When a question does not require a visual:

"visual_required": false,
"visual_type": null

Do NOT include "visual" when visual_required is false.

Never return an empty visual object.

Never return visual data for decorative purposes.

Never return Markdown, comments, headings, or text outside the JSON.

# LANGUAGE

The following fields MUST be written in {language}:

- question_text
- option_a
- option_b
- option_c
- option_d
- explanation
- visual labels/text when applicable

STRICT OUTPUT CONTRACT:

Return ONLY the final requested JSON object.

Do NOT include analysis, reasoning, planning, internal thinking, self-review,
verification, question-selection discussion, ordering discussion, or commentary
anywhere in the response.

Do NOT expose your reasoning process inside ANY JSON field.

Do NOT use JSON fields to store reasoning, planning, notes, validation,
drafting thoughts, or internal decisions.

Every JSON field must contain ONLY the final user-facing content required
by the requested schema.

--------------------------------------------------
JSON REQUIREMENTS
--------------------------------------------------

The response MUST be valid JSON.

The response must be directly parseable using JSON.parse().

Do NOT include Markdown code fences.

Do NOT include any text before or after the JSON object.

--------------------------------------------------
LATEX / BACKSLASH REQUIREMENTS
--------------------------------------------------

LaTeX may appear inside JSON string values.

Every LaTeX backslash MUST be escaped correctly for JSON.

For example:

CORRECT:
"$\\sqrt{15}$"

CORRECT:
"$\\angle ABC$"

CORRECT:
"$\\frac{1}{2}$"

CORRECT:
"$\\pi r^2$"

Any backslash used inside a JSON string must be represented as `\\`.

--------------------------------------------------
FINAL VALIDATION
--------------------------------------------------

Before returning the response, internally verify that:

1. Output ONLY valid, parseable JSON. Do not include any conversational text, internal monologues, preambles, or postscripts. 
2.Do not explain your thought process outside of the designated JSON fields.
3. Every JSON string is properly escaped.
4. Every LaTeX backslash inside a JSON string is escaped.
5. No reasoning or planning appears in any field.
6. No extra fields have been added.
7. No Markdown or commentary surrounds the JSON.
8. The final response contains only the requested JSON.
"""