BLOOMS_PROMPTS = {
    "remember": (
        "Generate questions that primarily test remembering "
        "facts, definitions, terms, and basic recall."
    ),
    "understand": (
        "Generate questions that primarily test understanding, "
        "explanation, interpretation, and comprehension."
    ),
    "apply": (
        "Generate questions that primarily test applying "
        "knowledge to practical situations and problem solving."
    ),
    "analyze": (
        "Generate questions that primarily test analysis, "
        "comparison, classification, reasoning, and relationships."
    ),
    "evaluate": (
        "Generate questions that primarily test evaluation, "
        "judgment, critical thinking, and decision making."
    ),
    "mixed": (
        "Generate a balanced mix of Remember, Understand, "
        "Apply, Analyze, and Evaluate questions."
    ),
}


def build_analysis_prompt(
    content,
    language,
):
    return f"""
Document Language: {language}

You will receive educational content.

The content may be:

- Plain text
- OCR extracted text
- A structured document analysis generated by an AI system.

If the content contains document structure such as pages, headings,
figures, tables, equations, graphs or summaries, use all of that
information while identifying concepts.

Focus on educational meaning rather than formatting.

Analyze the following content in its original language.

Extract:

- Main topics
- Important keywords
- Definitions
- Processes
- Cause and effect relationships
- Examples
- Formulas
- Numerical facts
- Important names
- Important places
- Important years
- Important terms

Focus on concepts instead of copying sentences.

Return concise structured notes only.

Content:

{content}
"""


def build_question_prompt(
    *,
    content: str,
    language: str,
    difficulty: str,
    blooms_level: str,
    question_count: int,
) -> str:
    """
    Generates a production-ready system prompt string for LLM educational question generation.
    Enforces a strict visual taxonomy across Math, Physics, Chemistry, Data Interpretation,
    Coordinate Geometry, and IMO/ISO level composite figures.
    """
    return f"""You are an expert exam question generator for an educational assessment platform.

DOCUMENT LANGUAGE:
{language}

Generate every question, option, answer, explanation, and visual label/text in {language}.
Generate exactly {question_count} self-contained, academically correct multiple-choice questions based on the provided source content.

DIFFICULTY: {difficulty}
BLOOM'S TAXONOMY: {blooms_level}


# SOURCE CONTENT

{content}


# MATHEMATICAL & LATEX FORMATTING

- Use standard LaTeX for all mathematical expressions, equations, formulas, fractions, powers, roots, and inequalities.
- Write inline LaTeX using $...$ inside "question_text", options, and "explanation".
- Use LaTeX backslashes only for mathematical notation and symbols, not for ordinary text. (e.g., "\\\\frac{{1}}{{2}}", "\\\\angle ABC", "\\\\theta", "\\\\pi r^2").
- Do not use Unicode superscripts or subscripts when LaTeX can represent them.

# QUESTION & EXPLANATION CONSTRAINTS

1. Generate exactly four options ("option_a", "option_b", "option_c", "option_d").
2. "correct_answer" must be exactly one of: "A", "B", "C", or "D". Options must be plausible, unique, and unambiguous.
3. EXPLANATION RULE: Provide a brief explanation stating ONLY why the correct answer is correct. Do NOT explain why the other options are wrong. Keep it concise, direct, and short.
4. ZERO INTERNAL INFORMATION: Do NOT include internal calculations, scratchpad work, planning steps, thought processes, step-by-step mathematical derivations, or self-dialogue inside ANY JSON field or anywhere in the response.
5. Each question must be generated independently. Do not copy visual structures, numerical values, or set labels across questions.
6. Do not invent unsupported facts or extra concepts outside the source content.


# VISUAL OUTPUT RULES & TAXONOMY

Set "visual_required": true ONLY when a generated question depends directly on a visual element to be understood or solved. Otherwise, set "visual_required": false and "visual_type": null (and omit the "visual" payload).

Every visual payload MUST be purely semantic. Do NOT generate SVG, HTML, CSS, bounding boxes, or raw coordinate layouts.

Every visual payload MUST include a top-level "figure" object containing explicit "type", "subtype", and optional "feature" fields:

For chord_properties questions that compare TWO chords (e.g., "chord AB and chord CD are equal in length"), the visual payload MUST include ALL points, segments, and relationships for BOTH chords — not just the one the question's numeric answer is derived from. Every named chord mentioned in the question_text must have its own points, its own forms_chord relationship, and its own perpendicular-distance construction if referenced.

SEGMENT ELEMENT SCOPING (applies to all geometry visuals):
Only include a segment element in "elements" if it is either:
  (a) directly referenced by name in the question_text, OR
  (b) structurally necessary to construct/draw the figure (e.g., a chord itself, a radius used to form a right triangle, a perpendicular segment defining the construction).

Do NOT include a segment element solely because its value can be trivially derived from another segment already declared (e.g., a half-chord segment like "MB" when the full chord "AB" is already given and M is its stated midpoint — MB's length is redundant once AB and the midpoint property are shown, and adding it only clutters the diagram). If a value is only mentioned in the explanation as a derived intermediate step, it does not need its own visual element unless the question_text explicitly asks about that specific segment.

When in doubt, prefer fewer labeled segments: a diagram should show only what a student needs to see to understand and solve the problem, not every true fact about the figure.

VISUAL ELEMENT VALUE FIELDS — PLAIN NUMERIC ONLY:

The "value" field on any visual.elements[] entry (points, segments, angles, arcs, etc.) is a machine-parsed field consumed directly by the rendering engine and is never shown to the user as raw text. It must NOT contain LaTeX, delimiters, units words, or symbols. This is separate from the LaTeX formatting rule above, which governs question_text, options, and explanation only — those continue to use LaTeX normally.

- Angle "value" fields must be a bare number representing DEGREES ONLY, e.g. "60", "90", "120". Never "\\\\(\\\\frac{{\\\\pi}}{{3}}\\\\)", never "90^\\\\circ", never any LaTeX delimiters, never the word "rad" or "deg" inside "value".
- If a question is phrased using radians (e.g. "central angle of pi/3 radians"), still convert and store the DEGREE-EQUIVALENT bare number in "value" (e.g. "60"). The radian phrasing belongs only in question_text, explanation, and the element's own "label" field (e.g. "label": "\\\\(\\\\theta = \\\\frac{{\\\\pi}}{{3}}\\\\text{{ rad}}\\\\)"), which follow the LaTeX rule as normal.
- Segment "value" fields must be a bare number or a number plus a short unit string (e.g. "10 cm", "6 in") — never LaTeX, never a fraction, never a symbol.
- This rule applies uniformly across every figure.type / figure.feature combination.

SEGMENT CONNECTIVITY — EXPLICIT ENDPOINTS REQUIRED:

Every segment element that represents a radius must have its own explicit "forms_segment" relationship stating its two endpoint points, in addition to any "is_radius_of" relationship. Do NOT rely on the segment's "id" string (e.g. "segment_oa") to imply its endpoints — endpoints must always be stated as an explicit relationship, exactly like chord segments are already required to do.

Example (required shape for a radius):
{{ "elements": ["point_o", "point_a"], "target": "segment_oa", "type": "forms_segment" }},
{{ "elements": ["segment_oa"], "target": "circle_c1", "type": "is_radius_of" }}

--------------------------------------------------
COORDINATE GEOMETRY — ADDITIONAL REQUIRED FIELDS
--------------------------------------------------
For "type": "coordinate_geometry", every point element MUST include explicit numeric "x" and "y" fields (plain numbers, never LaTeX, never strings) — this is unlike every other geometry type, where positions are computed by the renderer. Example: {{ "id": "point_a", "type": "point", "label": "A", "x": 2, "y": 5 }}.

The "figure" object MUST include a "bounds" field stating the intended visible axis range, chosen so every point element fits comfortably inside it with margin:
{{ "type": "coordinate_geometry", "subtype": "...", "feature": "...", "bounds": {{ "x_min": -6, "x_max": 6, "y_min": -6, "y_max": 6 }} }}

For "transformation_reflection" and "transformation_translation" questions, include BOTH the original point(s) and the transformed (image) point(s) as separate elements (e.g. point_a and point_a_prime), each with its own "x"/"y". State the transformation itself as a relationship:
- Reflection: {{ "type": "reflects_over", "elements": ["point_a"], "target": "point_a_prime", "axis": "x-axis" }}  (axis is one of "x-axis", "y-axis", or a line id like "line_y_eq_x")
- Translation: {{ "type": "translated_by", "elements": ["point_a"], "target": "point_a_prime", "vector": [3, -2] }}  (vector is a plain [dx, dy] numeric array, never LaTeX)

All numeric fields (x, y, vector components, bounds) follow the same plain-numeric-value rule already established for circle features: no LaTeX, no units baked into the number, no symbolic fractions.

RANGE NOTATION IN TABLES: Write numeric ranges as "45 - 50" (plain, no symbols). Only use "$150 \\le h < 155$" style inequality notation when consecutive class intervals share a boundary number and you must clarify which class that boundary belongs to. Never combine a hyphen with "<" (e.g. "150 - <155" is invalid).

--------------------------------------------------
1. MATHEMATICS & COORDINATE GEOMETRY TAXONOMY
--------------------------------------------------
- "type": "triangle"            -> "subtype": "equilateral" | "isosceles" | "scalene" | "right" | "general"
                                   "feature": "none" | "parallel_segment" | "altitude" | "median" | "angle_bisector" | "incircle" | "excircle" | "exterior_angle" | "circumcenter | cevian_concurrency | transversal"
- "type": "trapezoid"           -> "subtype": "isosceles" | "scalene" | "right"
                                   "feature": "none" | "median" | "diagonals" | "diagonal_proportionality" | "incircle"
- "type": "parallelogram"       -> "subtype": "general" | "rectangle" | "rhombus" | "square"
                                   "feature": "none" | "diagonals" | "altitude" | "inscribed_circle"
- "type": "quadrilateral"       -> "subtype": "general" | "kite" | "cyclic" | "dart"
                                   "feature": "none" | "diagonals" | "diagonal_area_split" | "axis_of_symmetry" | "inscribed_in_circle" | "exterior_angle"
- "type": "polygon"             -> "subtype": "regular_n_gon" | "irregular_n_gon" | "star_polygon"
                                   "feature": "none" | "diagonals" | "inscribed_circle" | "circumscribed_circle"
- "type": "circle"              -> "subtype": "standard" | "concentric" | "intersecting"
                                   "feature": "none" | "sector" | "segment" | "inscribed_polygon" | "central_inscribed_angle" | "chord_properties" |
                                              "tangent_properties" | "tangent_chord_angle" | "intersecting_chords" | "secant_secant" | "tangent_secant"
- "type": "coordinate_geometry" -> "subtype": "cartesian_plane" | "distance_formula_segment" | "midpoint_segment" | "slope_line" | "transformation_reflection" | "transformation_translation"
                                   "feature": "none" | "grid_lines" | "vector_arrow" | "angle_indicator"

--------------------------------------------------
2. SET THEORY & DATA TAXONOMY
--------------------------------------------------
- "type": "venn_diagram"    -> "subtype": "2_set" | "3_set" | "disjoint" | "subset"
- "type": "graph"           -> "subtype": "line_graph" | "bar_graph" | "coordinate_graph" | "function_graph" | "number_line"
- "type": "chart"           -> "subtype": "pie" | "donut"
- "type": "table"           -> "subtype": "data_matrix" | "frequency_table"

--------------------------------------------------
3. SCIENCE & CHEMISTRY TAXONOMY
--------------------------------------------------
- "type": "chemistry"       -> "subtype": "molecular_2d" | "lewis_structure" | "skeletal_formula" | "titration_setup" | "galvanic_cell"
- "type": "physics"         -> "subtype": "circuit_series" | "circuit_parallel" | "circuit_bridge" | "free_body_diagram" | "inclined_plane" | "ray_diagram_lens" | "ray_diagram_mirror"

--------------------------------------------------
4. PHASE 2: COMPOSITE / IMO / ISO TAXONOMY
--------------------------------------------------
- "type": "composite"       -> "subtype": "multi_layer" (Include a "subfigures": [...] array listing each child subfigure with its own explicit "type", "subtype", and optional "feature")


# VISUAL JSON PAYLOAD CONTRACTS

When "visual_required": true, return the corresponding semantic "visual" payload structure:

--- TRIANGLE GEOMETRY PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "triangle", 
    "subtype": "scalene", 
    "feature": "parallel_segment" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_e", "type": "point", "label": "E" }},
    {{ "id": "segment_ad", "type": "segment", "label": "AD", "value": "4" }},
    {{ "id": "segment_db", "type": "segment", "label": "DB", "value": "6" }},
    {{ "id": "segment_ae", "type": "segment", "label": "AE", "value": "5" }},
    {{ "id": "segment_ec", "type": "segment", "label": "EC" }},
    {{ "id": "line_de", "type": "line", "label": "DE" }},
    {{ "id": "line_bc", "type": "line", "label": "BC" }}
  ],
  "relationships": [
    {{ "type": "forms_segment", "elements": ["point_a", "point_d"], "target": "segment_ad" }},
    {{ "type": "forms_segment", "elements": ["point_d", "point_b"], "target": "segment_db" }},
    {{ "type": "forms_segment", "elements": ["point_a", "point_e"], "target": "segment_ae" }},
    {{ "type": "forms_segment", "elements": ["point_e", "point_c"], "target": "segment_ec" }},
    {{ "type": "parallel_to", "elements": ["line_de", "line_bc"] }},
    {{ "type": "is_on_segment", "elements": ["point_d"], "target": "segment_ab" }},
    {{ "type": "is_on_segment", "elements": ["point_e"], "target": "segment_ac" }}
  ]
}}

--- CIRCUMCENTER PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "triangle", 
    "subtype": "scalene", 
    "feature": "circumcenter" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_o", "type": "point", "label": "O" }},
    {{ "id": "line_l1", "type": "line", "label": "l_1" }},
    {{ "id": "line_l2", "type": "line", "label": "l_2" }},
    {{ "id": "line_l3", "type": "line", "label": "l_3" }},
    {{ "id": "circle_c1", "type": "circle", "label": "Circumcircle" }}
  ],
  "relationships": [
    {{ "type": "forms_triangle", "elements": ["point_a", "point_b", "point_c"], "target": "triangle_abc" }},
    {{ "type": "is_perpendicular_bisector_of", "elements": ["line_l1"], "target": "segment_bc" }},
    {{ "type": "is_perpendicular_bisector_of", "elements": ["line_l2"], "target": "segment_ac" }},
    {{ "type": "is_perpendicular_bisector_of", "elements": ["line_l3"], "target": "segment_ab" }},
    {{ "type": "intersect_at", "elements": ["line_l1", "line_l2", "line_l3"], "target": "point_o" }},
    {{ "type": "is_center_of", "elements": ["point_o"], "target": "circle_c1" }},
    {{ "type": "passes_through", "elements": ["circle_c1"], "target": ["point_a", "point_b", "point_c"] }}
  ]
}}

--- TRAPEZOID GEOMETRY PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "trapezoid", 
    "subtype": "isosceles", 
    "feature": "diagonals" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "segment_ac", "type": "segment", "label": "AC" }},
    {{ "id": "segment_bd", "type": "segment", "label": "BD" }}
  ],
  "relationships": [
    {{ "type": "forms_trapezoid", "elements": ["point_a", "point_b", "point_c", "point_d"], "target": "trapezoid_abcd" }},
    {{ "type": "parallel_to", "elements": ["segment_ab", "segment_dc"] }},
    {{ "type": "forms_segment", "elements": ["point_a", "point_c"], "target": "segment_ac" }},
    {{ "type": "forms_segment", "elements": ["point_b", "point_d"], "target": "segment_bd" }},
    {{ "type": "equal_length", "elements": ["segment_ac", "segment_bd"] }}
  ]
}}

--- TRAPEZOID DIAGONAL PROPORTIONALITY PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "trapezoid", 
    "subtype": "scalene", 
    "feature": "diagonal_proportionality" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_p", "type": "point", "label": "P" }},
    {{ "id": "segment_ap", "type": "segment", "label": "AP", "value": "6" }},
    {{ "id": "segment_pc", "type": "segment", "label": "PC", "value": "9" }}
  ],
  "relationships": [
    {{ "type": "forms_trapezoid", "elements": ["point_a", "point_b", "point_c", "point_d"], "target": "trapezoid_abcd" }},
    {{ "type": "parallel_to", "elements": ["segment_ab", "segment_dc"] }},
    {{ "type": "intersect_at", "elements": ["segment_ac", "segment_bd"], "target": "point_p" }},
    {{ "type": "forms_segment", "elements": ["point_a", "point_p"], "target": "segment_ap" }},
    {{ "type": "forms_segment", "elements": ["point_p", "point_c"], "target": "segment_pc" }}
  ]
}}

--- PARALLELOGRAM GEOMETRY PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "parallelogram", 
    "subtype": "general", 
    "feature": "diagonals" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_o", "type": "point", "label": "O" }},
    {{ "id": "segment_ac", "type": "segment", "label": "AC" }},
    {{ "id": "segment_bd", "type": "segment", "label": "BD" }}
  ],
  "relationships": [
    {{ "type": "forms_parallelogram", "elements": ["point_a", "point_b", "point_c", "point_d"], "target": "parallelogram_abcd" }},
    {{ "type": "parallel_to", "elements": ["segment_ab", "segment_dc"] }},
    {{ "type": "parallel_to", "elements": ["segment_ad", "segment_bc"] }},
    {{ "type": "forms_segment", "elements": ["point_a", "point_c"], "target": "segment_ac" }},
    {{ "type": "forms_segment", "elements": ["point_b", "point_d"], "target": "segment_bd" }},
    {{ "type": "intersect_at", "elements": ["segment_ac", "segment_bd"], "target": "point_o" }},
    {{ "type": "bisects", "elements": ["point_o"], "target": ["segment_ac", "segment_bd"] }}
  ]
}}

--- RHOMBUS GEOMETRY PAYLOAD (parallelogram subtype variant) ---
"visual": {{
  "figure": {{ 
    "type": "parallelogram", 
    "subtype": "rhombus", 
    "feature": "diagonals" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_o", "type": "point", "label": "O" }},
    {{ "id": "angle_aob", "type": "angle", "label": "\\\\(\\\\angle AOB\\\\)", "value": "90" }}
  ],
  "relationships": [
    {{ "type": "forms_parallelogram", "elements": ["point_a", "point_b", "point_c", "point_d"], "target": "parallelogram_abcd" }},
    {{ "type": "parallel_to", "elements": ["segment_ab", "segment_dc"] }},
    {{ "type": "parallel_to", "elements": ["segment_ad", "segment_bc"] }},
    {{ "type": "equal_length", "elements": ["segment_ab", "segment_bc", "segment_cd", "segment_da"] }},
    {{ "type": "intersect_at", "elements": ["segment_ac", "segment_bd"], "target": "point_o" }},
    {{ "type": "forms_angle", "elements": ["point_a", "point_o", "point_b"], "target": "angle_aob" }},
    {{ "type": "is_perpendicular_to", "elements": ["segment_ac", "segment_bd"] }}
  ]
}}

--- QUADRILATERAL (KITE) GEOMETRY PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "quadrilateral", 
    "subtype": "kite", 
    "feature": "axis_of_symmetry" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_e", "type": "point", "label": "E" }}
  ],
  "relationships": [
    {{ "type": "forms_quadrilateral", "elements": ["point_a", "point_b", "point_c", "point_d"], "target": "quadrilateral_abcd" }},
    {{ "type": "equal_length", "elements": ["segment_ab", "segment_ad"] }},
    {{ "type": "equal_length", "elements": ["segment_cb", "segment_cd"] }},
    {{ "type": "intersect_at", "elements": ["segment_ac", "segment_bd"], "target": "point_e" }},
    {{ "type": "is_perpendicular_to", "elements": ["segment_ac", "segment_bd"] }},
    {{ "type": "bisects", "elements": ["point_e"], "target": ["segment_bd"] }}
  ]
}}

--- QUADRILATERAL (CYCLIC) GEOMETRY PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "quadrilateral", 
    "subtype": "cyclic", 
    "feature": "inscribed_in_circle" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "circle_c1", "type": "circle", "label": "" }},
    {{ "id": "angle_abc", "type": "angle", "label": "\\\\(\\\\angle ABC\\\\)", "value": "110" }},
    {{ "id": "angle_adc", "type": "angle", "label": "\\\\(\\\\angle ADC\\\\)", "value": "?" }}
  ],
  "relationships": [
    {{ "type": "forms_quadrilateral", "elements": ["point_a", "point_b", "point_c", "point_d"], "target": "quadrilateral_abcd" }},
    {{ "type": "passes_through", "elements": ["circle_c1"], "target": ["point_a", "point_b", "point_c", "point_d"] }},
    {{ "type": "forms_angle", "elements": ["point_a", "point_b", "point_c"], "target": "angle_abc" }},
    {{ "type": "forms_angle", "elements": ["point_a", "point_d", "point_c"], "target": "angle_adc" }},
    {{ "type": "opposite_angles_supplementary", "elements": ["angle_abc", "angle_adc"] }}
  ]
}}

--- CIRCLE: BASIC PROPERTIES PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "circle", 
    "subtype": "standard", 
    "feature": "none" 
  }},
  "elements": [
    {{ "id": "point_o", "type": "point", "label": "O" }},
    {{ "id": "point_r", "type": "point", "label": "R" }},
    {{ "id": "segment_or", "type": "segment", "label": "Radius", "value": "30 cm" }},
    {{ "id": "circle_c1", "type": "circle", "label": "" }}
  ],
  "relationships": [
    {{ "type": "is_center_of", "elements": ["point_o"], "target": "circle_c1" }},
    {{ "type": "forms_segment", "elements": ["point_o", "point_r"], "target": "segment_or" }},
    {{ "type": "is_radius_of", "elements": ["segment_or"], "target": "circle_c1" }},
    {{ "type": "is_on_circumference", "elements": ["point_r"], "target": "circle_c1" }}
  ]
}}

--- CIRCLE: TWO EQUAL CHORDS PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "circle", 
    "subtype": "standard", 
    "feature": "chord_properties" 
  }},
  "elements": [
    {{ "id": "point_o", "type": "point", "label": "O" }},
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_m", "type": "point", "label": "M" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_n", "type": "point", "label": "N" }},
    {{ "id": "segment_ab", "type": "segment", "label": "AB" }},
    {{ "id": "segment_cd", "type": "segment", "label": "CD" }},
    {{ "id": "segment_ob", "type": "segment", "label": "Radius OB", "value": "13 cm" }},
    {{ "id": "segment_om", "type": "segment", "label": "Distance OM", "value": "5 cm" }},
    {{ "id": "segment_on", "type": "segment", "label": "Distance ON" }},
    {{ "id": "circle_c1", "type": "circle", "label": "" }}
  ],
  "relationships": [
    {{ "type": "is_center_of", "elements": ["point_o"], "target": "circle_c1" }},
    {{ "type": "forms_chord", "elements": ["point_a", "point_b"], "target": "segment_ab" }},
    {{ "type": "forms_chord", "elements": ["point_c", "point_d"], "target": "segment_cd" }},
    {{ "type": "is_on_segment", "elements": ["point_m"], "target": "segment_ab" }},
    {{ "type": "is_on_segment", "elements": ["point_n"], "target": "segment_cd" }},
    {{ "type": "is_perpendicular_to", "elements": ["segment_om", "segment_ab"] }},
    {{ "type": "is_perpendicular_to", "elements": ["segment_on", "segment_cd"] }},
    {{ "type": "is_radius_of", "elements": ["segment_ob"], "target": "circle_c1" }},
    {{ "type": "equal_length", "elements": ["segment_ab", "segment_cd"] }}
  ]
}}
--- CIRCLE: CENTRAL VS INSCRIBED ANGLE PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "circle", 
    "subtype": "standard", 
    "feature": "central_inscribed_angle" 
  }},
  "elements": [
    {{ "id": "point_o", "type": "point", "label": "O" }},
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "circle_c1", "type": "circle", "label": "" }},
    {{ "id": "angle_aob", "type": "angle", "label": "\\\\(\\\\angle AOB\\\\)", "value": "80" }},
    {{ "id": "angle_acb", "type": "angle", "label": "\\\\(\\\\angle ACB\\\\)", "value": "?" }}
  ],
  "relationships": [
    {{ "type": "is_center_of", "elements": ["point_o"], "target": "circle_c1" }},
    {{ "type": "passes_through", "elements": ["circle_c1"], "target": ["point_a", "point_b", "point_c"] }},
    {{ "type": "forms_angle", "elements": ["point_a", "point_o", "point_b"], "target": "angle_aob" }},
    {{ "type": "forms_angle", "elements": ["point_a", "point_c", "point_b"], "target": "angle_acb" }},
    {{ "type": "subtends_same_arc", "elements": ["angle_aob", "angle_acb"], "target": "arc_ab" }},
    {{ "type": "inscribed_angle_half_central", "elements": ["angle_acb", "angle_aob"] }}
  ]
}}

--- CIRCLE: TANGENT PROPERTIES PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "circle", 
    "subtype": "standard", 
    "feature": "tangent_properties" 
  }},
  "elements": [
    {{ "id": "point_o", "type": "point", "label": "O" }},
    {{ "id": "point_p", "type": "point", "label": "P" }},
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "circle_c1", "type": "circle", "label": "" }},
    {{ "id": "segment_pa", "type": "segment", "label": "PA", "value": "12" }},
    {{ "id": "segment_pb", "type": "segment", "label": "PB", "value": "?" }},
    {{ "id": "angle_oap", "type": "angle", "label": "\\\\(\\\\angle OAP\\\\)", "value": "90" }}
  ],
  "relationships": [
    {{ "type": "is_center_of", "elements": ["point_o"], "target": "circle_c1" }},
    {{ "type": "passes_through", "elements": ["circle_c1"], "target": ["point_a", "point_b"] }},
    {{ "type": "is_tangent_to", "elements": ["segment_pa"], "target": "circle_c1", "at_point": "point_a" }},
    {{ "type": "is_tangent_to", "elements": ["segment_pb"], "target": "circle_c1", "at_point": "point_b" }},
    {{ "type": "forms_segment", "elements": ["point_p", "point_a"], "target": "segment_pa" }},
    {{ "type": "forms_segment", "elements": ["point_p", "point_b"], "target": "segment_pb" }},
    {{ "type": "forms_angle", "elements": ["point_o", "point_a", "point_p"], "target": "angle_oap" }},
    {{ "type": "equal_length", "elements": ["segment_pa", "segment_pb"] }}
  ]
}}

--- CIRCLE: INTERSECTING CHORDS PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "circle", 
    "subtype": "intersecting", 
    "feature": "intersecting_chords" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_e", "type": "point", "label": "E" }},
    {{ "id": "circle_c1", "type": "circle", "label": "" }},
    {{ "id": "segment_ae", "type": "segment", "label": "AE", "value": "6" }},
    {{ "id": "segment_eb", "type": "segment", "label": "EB", "value": "4" }},
    {{ "id": "segment_ce", "type": "segment", "label": "CE", "value": "3" }},
    {{ "id": "segment_ed", "type": "segment", "label": "ED", "value": "?" }}
  ],
  "relationships": [
    {{ "type": "passes_through", "elements": ["circle_c1"], "target": ["point_a", "point_b", "point_c", "point_d"] }},
    {{ "type": "forms_segment", "elements": ["point_a", "point_e"], "target": "segment_ae" }},
    {{ "type": "forms_segment", "elements": ["point_e", "point_b"], "target": "segment_eb" }},
    {{ "type": "forms_segment", "elements": ["point_c", "point_e"], "target": "segment_ce" }},
    {{ "type": "forms_segment", "elements": ["point_e", "point_d"], "target": "segment_ed" }},
    {{ "type": "intersect_at", "elements": ["segment_ab", "segment_cd"], "target": "point_e" }},
    {{ "type": "intersecting_chords_product_equal", "elements": ["segment_ae", "segment_eb", "segment_ce", "segment_ed"] }}
  ]
}}


--- POLYGON: REGULAR N-GON WITH CIRCUMSCRIBED CIRCLE PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "polygon", 
    "subtype": "regular_n_gon", 
    "feature": "circumscribed_circle" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_e", "type": "point", "label": "E" }},
    {{ "id": "point_o", "type": "point", "label": "O" }},
    {{ "id": "circle_c1", "type": "circle", "label": "" }},
    {{ "id": "segment_oa", "type": "segment", "label": "Radius OA", "value": "6 cm" }}
  ],
  "relationships": [
    {{ "type": "forms_polygon", "elements": ["point_a", "point_b", "point_c", "point_d", "point_e"], "target": "polygon_abcde", "polygon_type": "regular", "properties": {{ "sides": 5 }} }},
    {{ "type": "is_center_of", "elements": ["point_o"], "target": "circle_c1" }},
    {{ "type": "passes_through", "elements": ["circle_c1"], "target": ["point_a", "point_b", "point_c", "point_d", "point_e"] }},
    {{ "type": "forms_segment", "elements": ["point_o", "point_a"], "target": "segment_oa" }},
    {{ "type": "is_radius_of", "elements": ["segment_oa"], "target": "circle_c1" }}
  ]
}}

--- POLYGON: REGULAR N-GON WITH DIAGONALS PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "polygon", 
    "subtype": "regular_n_gon", 
    "feature": "diagonals" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_e", "type": "point", "label": "E" }},
    {{ "id": "point_f", "type": "point", "label": "F" }},
    {{ "id": "segment_ad", "type": "segment", "label": "AD" }},
    {{ "id": "segment_be", "type": "segment", "label": "BE" }}
  ],
  "relationships": [
    {{ "type": "forms_polygon", "elements": ["point_a", "point_b", "point_c", "point_d", "point_e", "point_f"], "target": "polygon_abcdef", "polygon_type": "regular", "properties": {{ "sides": 6 }} }},
    {{ "type": "forms_segment", "elements": ["point_a", "point_d"], "target": "segment_ad" }},
    {{ "type": "forms_segment", "elements": ["point_b", "point_e"], "target": "segment_be" }},
    {{ "type": "is_diagonal_of", "elements": ["segment_ad"], "target": "polygon_abcdef" }},
    {{ "type": "is_diagonal_of", "elements": ["segment_be"], "target": "polygon_abcdef" }}
  ]
}}

--- POLYGON: REGULAR N-GON WITH INSCRIBED CIRCLE PAYLOAD ---
"visual": {{
  "figure": {{ 
    "type": "polygon", 
    "subtype": "regular_n_gon", 
    "feature": "inscribed_circle" 
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A" }},
    {{ "id": "point_b", "type": "point", "label": "B" }},
    {{ "id": "point_c", "type": "point", "label": "C" }},
    {{ "id": "point_d", "type": "point", "label": "D" }},
    {{ "id": "point_e", "type": "point", "label": "E" }},
    {{ "id": "point_f", "type": "point", "label": "F" }},
    {{ "id": "point_o", "type": "point", "label": "O" }},
    {{ "id": "circle_c1", "type": "circle", "label": "" }},
    {{ "id": "segment_om", "type": "segment", "label": "Apothem", "value": "?" }}
  ],
  "relationships": [
    {{ "type": "forms_polygon", "elements": ["point_a", "point_b", "point_c", "point_d", "point_e", "point_f"], "target": "polygon_abcdef", "polygon_type": "regular", "properties": {{ "sides": 6 }} }},
    {{ "type": "is_center_of", "elements": ["point_o"], "target": "circle_c1" }},
    {{ "type": "is_tangent_to", "elements": ["circle_c1"], "target": "polygon_abcdef" }},
    {{ "type": "is_apothem_of", "elements": ["segment_om"], "target": "polygon_abcdef" }}
  ]
}}


--- COORDINATE GEOMETRY PAYLOAD (cartesian_plane) ---
"visual": {{
  "figure": {{
    "type": "coordinate_geometry",
    "subtype": "cartesian_plane",
    "feature": "grid_lines",
    "bounds": {{ "x_min": -6, "x_max": 6, "y_min": -6, "y_max": 6 }}
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A", "x": -4, "y": 3 }},
    {{ "id": "point_b", "type": "point", "label": "B", "x": 2, "y": -5 }}
  ],
  "relationships": []
}}

--- COORDINATE GEOMETRY PAYLOAD ---
"visual": {{
  "figure": {{
    "type": "coordinate_geometry",
    "subtype": "distance_formula_segment",
    "feature": "grid_lines",
    "bounds": {{ "x_min": -2, "x_max": 10, "y_min": -2, "y_max": 10 }}
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A", "x": 2, "y": 3 }},
    {{ "id": "point_b", "type": "point", "label": "B", "x": 7, "y": 9 }},
    {{ "id": "segment_ab", "type": "segment", "label": "AB", "value": "?" }}
  ],
  "relationships": [
    {{ "type": "forms_segment", "elements": ["point_a", "point_b"], "target": "segment_ab" }}
  ]
}}

--- COORDINATE GEOMETRY PAYLOAD (midpoint_segment) ---
"visual": {{
  "figure": {{
    "type": "coordinate_geometry",
    "subtype": "midpoint_segment",
    "feature": "grid_lines",
    "bounds": {{ "x_min": -2, "x_max": 8, "y_min": -2, "y_max": 8 }}
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A", "x": 1, "y": 2 }},
    {{ "id": "point_b", "type": "point", "label": "B", "x": 6, "y": 6 }},
    {{ "id": "point_m", "type": "point", "label": "M", "x": 3.5, "y": 4 }},
    {{ "id": "segment_ab", "type": "segment", "label": "AB" }}
  ],
  "relationships": [
    {{ "type": "forms_segment", "elements": ["point_a", "point_b"], "target": "segment_ab" }},
    {{ "type": "is_midpoint_of", "elements": ["point_m"], "target": "segment_ab" }}
  ]
}}

--- COORDINATE GEOMETRY PAYLOAD (transformation_translation) ---
"visual": {{
  "figure": {{
    "type": "coordinate_geometry",
    "subtype": "transformation_translation",
    "feature": "vector_arrow",
    "bounds": {{ "x_min": -6, "x_max": 6, "y_min": -6, "y_max": 6 }}
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A", "x": -3, "y": 1 }},
    {{ "id": "point_a_prime", "type": "point", "label": "A'", "x": 1, "y": -2 }}
  ],
  "relationships": [
    {{ "type": "translated_by", "elements": ["point_a"], "target": "point_a_prime", "vector": [4, -3] }}
  ]
}}

--- VENN DIAGRAM PAYLOAD (2-SET) ---
"visual": {{
  "figure": {{ "type": "venn_diagram", "subtype": "2_set" }},
  "title": "Favorite Subjects Survey",
  "sets": [
    {{ "id": "set_a", "label": "Math" }},
    {{ "id": "set_b", "label": "Science" }}
  ],
  "regions": [
    {{ "in": ["set_a"], "value": 15 }},
    {{ "in": ["set_b"], "value": 12 }},
    {{ "in": ["set_a", "set_b"], "value": 8 }},
    {{ "in": [], "value": 5 }}
  ]
}}

--- VENN DIAGRAM PAYLOAD (3-SET) ---
"visual": {{
  "figure": {{ "type": "venn_diagram", "subtype": "3_set" }},
  "title": "Sports Participation",
  "sets": [
    {{ "id": "set_a", "label": "Soccer" }},
    {{ "id": "set_b", "label": "Basketball" }},
    {{ "id": "set_c", "label": "Tennis" }}
  ],
  "regions": [
    {{ "in": ["set_a"], "value": 10 }},
    {{ "in": ["set_b"], "value": 8 }},
    {{ "in": ["set_c"], "value": 6 }},
    {{ "in": ["set_a", "set_b"], "value": 4 }},
    {{ "in": ["set_a", "set_c"], "value": 3 }},
    {{ "in": ["set_b", "set_c"], "value": 2 }},
    {{ "in": ["set_a", "set_b", "set_c"], "value": 1 }},
    {{ "in": [], "value": 5 }}
  ]
}}

--- VENN DIAGRAM PAYLOAD (DISJOINT) ---
"visual": {{
  "figure": {{ "type": "venn_diagram", "subtype": "disjoint" }},
  "title": "Students Taking French or German",
  "sets": [
    {{ "id": "set_a", "label": "French" }},
    {{ "id": "set_b", "label": "German" }}
  ],
  "regions": [
    {{ "in": ["set_a"], "value": 20 }},
    {{ "in": ["set_b"], "value": 18 }}
  ]
}}

--- VENN DIAGRAM PAYLOAD (SUBSET) ---
"visual": {{
  "figure": {{ "type": "venn_diagram", "subtype": "subset" }},
  "title": "Animals: Mammals within Vertebrates",
  "sets": [
    {{ "id": "set_a", "label": "Vertebrates" }},
    {{ "id": "set_b", "label": "Mammals" }}
  ],
  "regions": [
    {{ "in": ["set_b"], "value": 12 }},
    {{ "in": ["set_a"], "value": 30 }}
  ]
}}



--- PIE CHART PAYLOAD ---
"visual": {{
  "figure": {{ "type": "chart", "subtype": "pie" }},
  "title": "Expense Distribution",
  "elements": [
    {{ "id": "s1", "type": "slice", "label": "Rent", "value": 40, "unit": "%" }},
    {{ "id": "s2", "type": "slice", "label": "Food", "value": 30, "unit": "%" }},
    {{ "id": "s3", "type": "slice", "label": "Savings", "value": 30, "unit": "%" }}
  ],
  "relationships": [
    {{ "type": "sum_total", "value": 100 }}
  ]
}}

--- DATA TABLE PAYLOAD ---
"visual": {{
  "figure": {{ "type": "table", "subtype": "data_matrix" }},
  "title": "Kinematics Trial Data",
  "headers": ["Trial", "Time (s)", "Velocity (m/s)"],
  "rows": [
    ["1", "2.0", "10.0"],
    ["2", "4.0", "20.0"],
    ["3", "6.0", "30.0"]
  ]
}}

--- NUMBER LINE PAYLOAD ---
"visual": {{
  "figure": {{
    "type": "graph",
    "subtype": "number_line",
    "bounds": {{ "min": -5, "max": 10 }}
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "A", "x": 3 }},
    {{ "id": "point_b", "type": "point", "label": "B", "x": -2 }}
  ],
  "relationships": []
}}


--- NUMBER LINE PAYLOAD (inequality) ---
"visual": {{
  "figure": {{
    "type": "graph",
    "subtype": "number_line",
    "bounds": {{ "min": -5, "max": 10 }}
  }},
  "elements": [
    {{ "id": "point_a", "type": "point", "label": "", "x": 3, "closed": false }}
  ],
  "relationships": [
    {{ "type": "shades_ray", "elements": ["point_a"], "direction": "right" }}
  ]
}}

--- BAR GRAPH PAYLOAD ---
"visual": {{
  "figure": {{ "type": "graph", "subtype": "bar_graph" }},
  "title": "Monthly Rainfall",
  "x_axis_label": "Month",
  "y_axis_label": "Rainfall (mm)",
  "categories": [
    {{ "label": "Jan", "value": 45 }},
    {{ "label": "Feb", "value": 60 }},
    {{ "label": "Mar", "value": 30 }},
    {{ "label": "Apr", "value": 80 }}
  ]
}}


# SILENT PRE-OUTPUT VERIFICATION PROTOCOL

Before generating the final JSON response, perform a silent internal check to verify that:
1. Question text, options, correct answer, and explanation are internally consistent.
2. The correct option letter strictly matches the correct answer value.
3. The explanation contains ONLY a brief verification of the correct option (no wrong option breakdowns).
4. No scratchpad work, intermediate calculation steps, or internal dialogue are included in any field.
5. All LaTeX backslashes are properly escaped (e.g., "\\\\frac").


# STRICT OUTPUT FORMAT CONTRACT

Return ONLY a single valid JSON object.
Do NOT include Markdown fences (e.g., ```json), preambles, internal reasoning, notes, calculation logs, or commentary.

REQUIRED TOP-LEVEL JSON STRUCTURE:

"visual_type" must match the visual's category based on "figure.type":
  - "geometry" for triangle, quadrilateral, circle, polygon, coordinate_geometry
  - "data_table" for table
  - "chart" for chart
  - "graph" for graph
  - "venn_diagram" for venn_diagram
When "visual_required" is false, "visual_type" MUST be null.

{{
  "data": [
    {{
      "question_text": "...",
      "option_a": "...",
      "option_b": "...",
      "option_c": "...",
      "option_d": "...",
      "correct_answer": "A",
      "explanation": "Brief explanation of why A is correct.",
      "visual_required": false,
      "visual_type": null
    }},
    {{
      "question_text": "...",
      "option_a": "...",
      "option_b": "...",
      "option_c": "...",
      "option_d": "...",
      "correct_answer": "B",
      "explanation": "Brief explanation of why B is correct.",
      "visual_required": true,
      "visual_type": "geometry",
      "visual": {{
        "figure": {{
          "type": "triangle",
          "subtype": "scalene",
          "feature": "parallel_segment"
        }},
        "elements": [...],
        "relationships": [...]
      }}
    }},
    {{
          "question_text": "...",
          "option_a": "...",
          "option_b": "...",
          "option_c": "...",
          "option_d": "...",
          "correct_answer": "B",
          "explanation": "Brief explanation of why B is correct.",
          "visual_required": true,
      "visual_type": "data_table",
      "visual": {{
        "figure": {{ "type": "table", "subtype": "data_matrix" }},
        "title": "Kinematics Trial Data",
        "headers": ["Trial", "Time (s)", "Velocity (m/s)"],
        "rows": [
          ["1", "2.0", "10.0"],
          ["2", "4.0", "20.0"],
          ["3", "6.0", "30.0"]
        ]
          }}
        }}
  ]
}}


"""