"""Blooms level add in ai generation requests

Revision ID: 0e70f5692059
Revises: abf7c9640d76
Create Date: 2026-07-12 19:02:53.132227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e70f5692059'
down_revision = 'abf7c9640d76'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("ai_generation_requests") as batch_op:
        batch_op.add_column(
            sa.Column(
                "blooms_level",
                sa.String(length=30),
                nullable=False,
                server_default="mixed",
            )
        )

    with op.batch_alter_table("ai_generation_requests") as batch_op:
        batch_op.alter_column(
            "blooms_level",
            server_default=None,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation_requests', schema=None) as batch_op:
        batch_op.drop_column('blooms_level')

    # ### end Alembic commands ###
