"""Add document language

Revision ID: 243233943090
Revises: cd55da54b978
Create Date: 2026-07-07 22:36:32.594315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '243233943090'
down_revision = 'cd55da54b978'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_language', sa.String(length=30), nullable=False, server_default="english",))
        batch_op.alter_column( "document_language", server_default=None,)
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_school_class_roll', type_='unique')
        batch_op.create_unique_constraint('uq_student_school_class_section_roll', ['school_id', 'school_class_id', 'school_section_id', 'roll_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_school_class_section_roll', type_='unique')
        batch_op.create_unique_constraint('uq_student_school_class_roll', ['school_id', 'student_class', 'roll_number'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('ai_generation_requests', schema=None) as batch_op:
        batch_op.drop_column('document_language')

    # ### end Alembic commands ###
