"""Update school usage unique constraint

Revision ID: 399bfe6c17f6
Revises: 853d04251251
Create Date: 2026-08-01 10:22:31.936188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '399bfe6c17f6'
down_revision = '853d04251251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_school_usage_school_id')
        batch_op.create_index(batch_op.f('ix_school_usage_school_id'), ['school_id'], unique=False)
        batch_op.create_unique_constraint('uq_school_usage_period', ['school_id', 'billing_period'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('school_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('school_usage', schema=None) as batch_op:
        batch_op.drop_constraint('uq_school_usage_period', type_='unique')
        batch_op.drop_index(batch_op.f('ix_school_usage_school_id'))
        batch_op.create_index('ix_school_usage_school_id', ['school_id'], unique=True)

    # ### end Alembic commands ###
