"""add additional attempt grants

Revision ID: 399c15f95bb3
Revises: d1a5d4330057
Create Date: 2026-07-09 11:08:54.356811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399c15f95bb3'
down_revision = 'd1a5d4330057'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('additional_attempt_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grant_uid', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('student_db_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('granted_attempts', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('granted_attempts > 0', name='ck_granted_attempts_positive'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['student_db_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_uid')
    )
    with op.batch_alter_table('additional_attempt_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_additional_attempt_grants_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_additional_attempt_grants_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_additional_attempt_grants_student_db_id'), ['student_db_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_additional_attempt_grants_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('additional_attempt_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_additional_attempt_grants_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_additional_attempt_grants_student_db_id'))
        batch_op.drop_index(batch_op.f('ix_additional_attempt_grants_school_id'))
        batch_op.drop_index(batch_op.f('ix_additional_attempt_grants_exam_id'))

    op.drop_table('additional_attempt_grants')
    # ### end Alembic commands ###
