"""create subscription plans table

Revision ID: 40ea3ea8d3bf
Revises: 399c15f95bb3
Create Date: 2026-07-10 10:10:21.513731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40ea3ea8d3bf'
down_revision = '399c15f95bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('yearly_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('monthly_ai_credits', sa.Integer(), nullable=False),
    sa.Column('max_students', sa.Integer(), nullable=False),
    sa.Column('max_teachers', sa.Integer(), nullable=False),
    sa.Column('max_classes', sa.Integer(), nullable=False),
    sa.Column('max_sections', sa.Integer(), nullable=False),
    sa.Column('max_pdf_pages', sa.Integer(), nullable=False),
    sa.Column('max_images_per_request', sa.Integer(), nullable=False),
    sa.Column('max_questions_per_generation', sa.Integer(), nullable=False),
    sa.Column('storage_mb', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_plans_plan_uid'), ['plan_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_plan_uid'))

    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
