"""create school subscriptions table

Revision ID: 412f0d327b97
Revises: 40ea3ea8d3bf
Create Date: 2026-07-10 10:29:12.125862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412f0d327b97'
down_revision = '40ea3ea8d3bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_uid', sa.String(length=36), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('billing_cycle', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_subscriptions_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_subscriptions_subscription_uid'), ['subscription_uid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_subscriptions_subscription_uid'))
        batch_op.drop_index(batch_op.f('ix_school_subscriptions_school_id'))

    op.drop_table('school_subscriptions')
    # ### end Alembic commands ###
