"""add students table and link attempts to students

Revision ID: 490d0938ba64
Revises: 7437347fedcc
Create Date: 2026-06-09 13:56:47.580020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490d0938ba64'
down_revision = '7437347fedcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_uid', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('student_class', sa.String(length=50), nullable=True),
    sa.Column('roll_number', sa.String(length=50), nullable=True),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_mobile'), ['mobile'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_student_uid'), ['student_uid'], unique=True)

    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_db_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'students', ['student_db_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('student_db_id')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_student_uid'))
        batch_op.drop_index(batch_op.f('ix_students_mobile'))

    op.drop_table('students')
    # ### end Alembic commands ###
