"""Add visual fields to QuestionModel

Revision ID: 4aceb2b9aaae
Revises: a1bed746ca30
Create Date: 2026-08-21 23:57:27.159083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aceb2b9aaae'
down_revision = 'a1bed746ca30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visual_required', sa.Boolean(), server_default=sa.text("false"), nullable=False))
        batch_op.add_column(sa.Column('visual_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('visual', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('visual')
        batch_op.drop_column('visual_type')
        batch_op.drop_column('visual_required')

    # ### end Alembic commands ###
