"""create school usage table

Revision ID: 53967577786b
Revises: d81a8461fb59
Create Date: 2026-07-10 10:55:14.595126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53967577786b'
down_revision = 'd81a8461fb59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('ai_credits_used', sa.Integer(), nullable=False),
    sa.Column('storage_used_mb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_usage_school_id'), ['school_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_usage_school_id'))

    op.drop_table('school_usage')
    # ### end Alembic commands ###
