"""add source_summary to ai_generation_request

Revision ID: 694dea77f5ec
Revises: a3b2fddff558
Create Date: 2026-06-18 13:22:41.560579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694dea77f5ec'
down_revision = 'a3b2fddff558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_summary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation_requests', schema=None) as batch_op:
        batch_op.drop_column('source_summary')

    # ### end Alembic commands ###
