"""Add registration mode and student unique constraint

Revision ID: 6e2ea28ca11b
Revises: d061dce406da
Create Date: 2026-07-03 16:40:47.718960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2ea28ca11b'
down_revision = 'd061dce406da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_mode', sa.String(length=20), nullable=False, server_default='open'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_student_school_class_roll', ['school_id', 'student_class', 'roll_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('uq_student_school_class_roll', type_='unique')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('registration_mode')

    # ### end Alembic commands ###
