"""add exam targets

Revision ID: 7ec95c1ce10d
Revises: a9e6365ebcf5
Create Date: 2026-07-06 18:29:40.005363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ec95c1ce10d'
down_revision = 'a9e6365ebcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('school_section_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['school_section_id'], ['school_sections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'school_class_id', 'school_section_id', name='uq_exam_target')
    )
    with op.batch_alter_table('exam_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_targets_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_targets_school_class_id'), ['school_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_targets_school_section_id'), ['school_section_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_targets_school_section_id'))
        batch_op.drop_index(batch_op.f('ix_exam_targets_school_class_id'))
        batch_op.drop_index(batch_op.f('ix_exam_targets_exam_id'))

    op.drop_table('exam_targets')
    # ### end Alembic commands ###
