"""add exam uid

Revision ID: 853d04251251
Revises: 0e70f5692059
Create Date: 2026-07-14 10:07:32.789684

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = '853d04251251'
down_revision = '0e70f5692059'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "exam_uid",
                sa.String(length=36),
                nullable=True,
            )
        )

    exam_table = sa.table(
        "exams",
        sa.column("id", sa.Integer),
        sa.column("exam_uid", sa.String),
    )

    connection = op.get_bind()

    rows = connection.execute(
        sa.select(exam_table.c.id)
    ).fetchall()

    for row in rows:
        connection.execute(
            exam_table.update()
            .where(exam_table.c.id == row.id)
            .values(
                exam_uid=str(uuid.uuid4())
            )
        )

    with op.batch_alter_table("exams", schema=None) as batch_op:
        batch_op.alter_column(
            "exam_uid",
            nullable=False,
        )

        batch_op.create_index(
            batch_op.f("ix_exams_exam_uid"),
            ["exam_uid"],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exams_exam_uid'))
        batch_op.drop_column('exam_uid')

    # ### end Alembic commands ###
