"""add ai bonous credit coulmn in school usage

Revision ID: 9088f72315c4
Revises: 53967577786b
Create Date: 2026-07-10 17:17:10.781583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9088f72315c4'
down_revision = '53967577786b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_ai_credits', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_usage', schema=None) as batch_op:
        batch_op.drop_column('bonus_ai_credits')

    # ### end Alembic commands ###
