"""add analysis_report to ai_generation_requests

Revision ID: a1bed746ca30
Revises: eb8d6810f65f
Create Date: 2026-08-06 21:03:55.040011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1bed746ca30'
down_revision = 'eb8d6810f65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis_report', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation_requests', schema=None) as batch_op:
        batch_op.drop_column('analysis_report')

    # ### end Alembic commands ###
