"""add ai generation requests

Revision ID: a3b2fddff558
Revises: 556c42495fb6
Create Date: 2026-06-17 16:29:40.331390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3b2fddff558'
down_revision = '556c42495fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('generated_questions', sa.JSON(), nullable=True),
    sa.Column('generation_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_generation_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_generation_requests_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_generation_requests_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_generation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_generation_requests_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_ai_generation_requests_school_id'))

    op.drop_table('ai_generation_requests')
    # ### end Alembic commands ###
