"""add school class and section to students

Revision ID: a9e6365ebcf5
Revises: e6e53340098b
Create Date: 2026-07-06 10:58:06.182456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e6365ebcf5'
down_revision = 'e6e53340098b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_class_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('school_section_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_school_class_id'), ['school_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_school_section_id'), ['school_section_id'], unique=False)
        batch_op.create_foreign_key(None, 'school_sections', ['school_section_id'], ['id'])
        batch_op.create_foreign_key(None, 'school_classes', ['school_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_school_section_id'))
        batch_op.drop_index(batch_op.f('ix_students_school_class_id'))
        batch_op.drop_column('school_section_id')
        batch_op.drop_column('school_class_id')

    # ### end Alembic commands ###
