"""add plan code to subscription plans

Revision ID: abf7c9640d76
Revises: 9088f72315c4
Create Date: 2026-07-10 18:09:28.162845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf7c9640d76'
down_revision = '9088f72315c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans') as batch_op:
        batch_op.add_column(
            sa.Column('plan_code', sa.String(length=30), nullable=True)
        )

    op.execute("""
    UPDATE subscription_plans
    SET plan_code = CASE name
        WHEN 'Trial' THEN 'TRIAL'
        WHEN 'Starter' THEN 'STARTER'
        WHEN 'Growth' THEN 'GROWTH'
        WHEN 'Professional' THEN 'PROFESSIONAL'
    END
    """)

    with op.batch_alter_table('subscription_plans') as batch_op:
        batch_op.alter_column(
            'plan_code',
            existing_type=sa.String(length=30),
            nullable=False
        )

    with op.batch_alter_table('subscription_plans') as batch_op:
        batch_op.create_index(
            batch_op.f('ix_subscription_plans_plan_code'),
            ['plan_code'],
            unique=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_plans_plan_code'))
        batch_op.drop_column('plan_code')

    # ### end Alembic commands ###
