"""remove class_name from exams

Revision ID: cd55da54b978
Revises: 7ec95c1ce10d
Create Date: 2026-07-06 21:05:50.443806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd55da54b978'
down_revision = '7ec95c1ce10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_column('class_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
