"""remove student_class from StudentModel

Revision ID: d1a5d4330057
Revises: 243233943090
Create Date: 2026-07-09 10:04:56.222730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1a5d4330057'
down_revision = '243233943090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('student_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_class', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
