"""create ai features table

Revision ID: d81a8461fb59
Revises: 412f0d327b97
Create Date: 2026-07-10 10:43:02.476307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81a8461fb59'
down_revision = '412f0d327b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_code', sa.String(length=50), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('credits_required', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_features_feature_code'), ['feature_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_features_feature_code'))

    op.drop_table('ai_features')
    # ### end Alembic commands ###
