"""add school sections

Revision ID: e6e53340098b
Revises: 8d58441c2d3a
Create Date: 2026-07-06 00:19:42.245107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e53340098b'
down_revision = '8d58441c2d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('school_class_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['school_class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_class_id', 'name', name='uq_school_section_name')
    )
    with op.batch_alter_table('school_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_sections_school_class_id'), ['school_class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_sections_school_id'), ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('school_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_sections_school_id'))
        batch_op.drop_index(batch_op.f('ix_school_sections_school_class_id'))

    op.drop_table('school_sections')
    # ### end Alembic commands ###
